//! REC-001: Self-improvement objective type.
//!
//! CSV guardrail: "Define self-improvement objective type (distinguish from
//!   ordinary objectives, repo target + trust-boundary impact)."
//! Caution: "Do not allow hidden self-modification."
//! auto_approval_policy: never_silent
//!
//! Acceptance: self-improvement objectives are a distinct type from ordinary
//! objectives, carrying repo-target binding and trust-boundary impact
//! assessment.  Every self-improvement objective must leave a durable
//! artifact (never_silent).

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Classifies whether an objective is ordinary work or self-improvement.
/// Self-improvement objectives require additional safety gates and
/// audit trail (CSV: "distinguish from ordinary objectives").
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "snake_case")]
pub enum ObjectiveClassification {
    /// Normal project work -- no special gates required.
    Ordinary,
    /// Self-improvement: the system is modifying its own behaviour,
    /// configuration, or code.  Requires safety gates (REC-003),
    /// repo-target policy (REC-002), and drift checks (REC-007).
    SelfImprovement,
}

/// Which trust boundary a self-improvement objective affects.
/// CSV: "repo target + trust-boundary impact".
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "snake_case")]
pub enum TrustBoundaryImpact {
    /// No boundary crossed -- internal tooling only.
    Internal,
    /// Crosses into policy enforcement code.
    PolicyEnforcement,
    /// Crosses into safety gate definitions.
    SafetyGate,
    /// Crosses into approval/governance logic.
    ApprovalGovernance,
    /// Crosses into worker dispatch or execution.
    ExecutionControl,
    /// Crosses into persistent state schemas.
    StateSchema,
    /// Crosses multiple trust boundaries.
    MultipleBoundaries,
}

/// Self-improvement objective.
///
/// A distinct objective type that captures repo target binding and
/// trust-boundary impact.  Every field required for audit trail
/// (never_silent: every recursive action must leave a durable artifact).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SelfImprovementObjective {
    /// Unique objective identifier (UUIDv7 recommended).
    pub objective_id: String,
    /// Classification: always `SelfImprovement` for this type.
    pub classification: ObjectiveClassification,
    /// Human-readable summary of the improvement goal.
    pub summary: String,
    /// Detailed rationale for why this improvement is needed.
    pub rationale: String,
    /// The repo target this objective modifies (package path, file glob, etc.).
    pub repo_target: String,
    /// Trust boundary impact assessment.
    pub trust_boundary_impact: TrustBoundaryImpact,
    /// Whether this objective was generated by a prior self-improvement loop.
    pub is_recursive: bool,
    /// If recursive, the parent objective that spawned this one.
    pub parent_objective_id: Option<String>,
    /// The safety gate level required (from REC-003).
    pub required_gate_level: String,
    /// Current status.
    pub status: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}
